### ISSUE TITLE
运行的时候出现

### ISSUE THREAD

**Issue by wuan11** [XYZliang/HUAWEI-STORE-GO#1]
Traceback (most recent call last):
  File "E:\HUAWEI-STORE-GO-main\HUAWEI STORE.py", line 215, in <module>
    for account, pwd in data.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by XYZliang** [comment]
我在多个系统中进行测试都没有发现这个问题。
这段代码是旧项目的，我一开始没有仔细看这里，我只能看浅层次看懂，百度看了一下后，暂时没发现有什么问题。
百度无果，大多数问题指向你用python打包时，pyinstaller版本太低。建议将python、selenium、pyinstaller升级到最新版本后再进行尝试。
感谢提醒，我仔细看了这里代码才发现。。。。这个py脚本是可以多线程多账号的～

**Comment by hacken156026692** [comment]
请问一下，我想用安卓手机进行抢购，请问，用python手机版或termux终端器，能实现吗？

**Comment by XYZliang** [comment]
> 请问一下，我想用安卓手机进行抢购，请问，用python手机版或termux终端器，能实现吗？

用termux给手机安装上相关环境是可以的，但我不确定有没有对应安卓手机上的webdriver。网络上有很多例子，我也没有仔细看，这些都超过我能力之外。

**Comment by drumzhang** [comment]
> Traceback (most recent call last):
> File "E:\HUAWEI-STORE-GO-main\HUAWEI STORE.py", line 215, in
> for account, pwd in data.items():
> AttributeError: 'str' object has no attribute 'items'

ACCOUNT必须是map

**Comment by vickyqi7** [comment]
请问py虽然跑起来了，但是就卡在了登陆后的那个个人主页里再也不动了。。。。为什么？

**Comment by XYZliang** [comment]
> 请问py虽然跑起来了，但是就卡在了登陆后的那个个人主页里再也不动了。。。。为什么？

最近都没去抢，刚刚试了下脚本好像没有问题。
个人主页？可以提供下这个网址我看看么～

有空我优化一下登陆成功跳转的逻辑。

**Comment by skklkim** [comment]
![github](https://user-images.githubusercontent.com/32292554/108797741-e7ed6000-75c6-11eb-9ef2-70d87d06400b.png)
请问我运行后打开chrome，报错了

**Comment by XYZliang** [comment]
> ![github](https://user-images.githubusercontent.com/32292554/108797741-e7ed6000-75c6-11eb-9ef2-70d87d06400b.png)
> 请问我运行后打开chrome，报错了

你的环境问题，百度了一下，可能情况有很多。大概率是因为，你的chrome_driver参数输错了，应该输入chromedriver.exe这个文件的位置，我看你输入的是chrome浏览器的文件位置。（我的描述可能误导了你，下一个版本我会改一下）

**Comment by skklkim** [comment]
非常感谢，我也百度解决了这个问题&nbsp;&nbsp;
目前脚本运行非常好&nbsp; 我也在学习python中&nbsp; 以后期待能跟你学习&nbsp;



---原始邮件---
发件人: "ZhangLiang"<notifications@github.com&gt;
发送时间: 2021年2月23日(周二) 下午4:41
收件人: "XYZliang/HUAWEI-STORE-GO"<HUAWEI-STORE-GO@noreply.github.com&gt;;
抄送: "skklkim"<38927172@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [XYZliang/HUAWEI-STORE-GO] 运行的时候出现 (#1)




  

 请问我运行后打开chrome，报错了
  
你的环境问题，百度了一下，可能情况有很多。大概率是因为，你的chrome_driver参数输错了，应该输入chromedriver.exe这个文件的位置，我看你输入的是chrome浏览器的文件位置。（我的描述可能误导了你，下一个版本我会改一下）

**Comment by XYZliang** [comment]
> 非常感谢，我也百度解决了这个问题&nbsp;&nbsp; 目前脚本运行非常好&nbsp; 我也在学习python中&nbsp; 以后期待能跟你学习&nbsp;
> […](#)

互相学习！
