### ISSUE TITLE
写的啥哦

### ISSUE THREAD

**Issue by h4onanh** [XYZliang/HUAWEI-STORE-GO#2]
成功跑起来，自动化登陆要验证码直接跳过去了，我手动挡登陆挂着到时间还是没买上，到时间就结束了

**Comment by XYZliang** [comment]
1.程序我换了很多设备都没有问题
2.登陆验证码部分偶尔会出问题，但是很少，你不提供细节我怎么帮你
3.晚上华为好像没有抢购吧？时间没到怎么抢
4.麻烦尊重别人的劳动成果
5.最后写的很清楚，有问题自己解决

**Comment by h4onanh** [comment]
你这个会自动化登陆必会出验证码（不是网页的问题应该，测试过手动打开登陆页），然后登陆不上就跳过了。
就算手动挡登陆到时间也没买，代码没报错，就是不买，我用的不是需要准点抢购的商品，只是正常的商品测试一下。
很尊重，搭环境都搭了半天
