### ISSUE TITLE
帅哥，为什么下载了包后，解压报错了

### ISSUE THREAD

**Issue by Newplaer** [XYZliang/HUAWEI-STORE-GO#4]

**Comment by XYZliang** [comment]
emmmmm，没有截图我也不知道。
压缩包是github自动生成的，一般来说没什么问题，可能是你的压缩软件有问题。
建议换一个压缩软件，比如Windows下的360压缩（360为数不多的良心软件了），mac下的maczip或者keka
或者，你直接点开[HUAWEI STORE GO.py](https://github.com/XYZliang/HUAWEI-STORE-GO/blob/main/HUAWEI%20STORE%20GO.py)单独下载这个py脚本就行了。

**Comment by Newplaer** [comment]
你好，下面给你贴下截图。
我也试试360压缩吧。&nbsp;目前我电脑上用的是winrar和banzip





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XYZliang/HUAWEI-STORE-GO"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 下午3:48
收件人:&nbsp;"XYZliang/HUAWEI-STORE-GO"<HUAWEI-STORE-GO@noreply.github.com&gt;;
抄送:&nbsp;"244083161"<244083161@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XYZliang/HUAWEI-STORE-GO] 帅哥，为什么下载了包后，解压报错了 (#4)





 
emmmmm，没有截图我也不知道。
 压缩包是github自动生成的，一般来说没什么问题，可能是你的压缩软件有问题。
 建议换一个压缩软件，比如Windows下的360压缩（360为数不多的良心软件了），mac下的maczip或者keka
 或者，你直接点开HUAWEI STORE GO.py单独下载这个py脚本就行了。

**Comment by Newplaer** [comment]
朋友，用360压缩&nbsp;解压也报错了。你这边能不能邮件发我一份






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XYZliang/HUAWEI-STORE-GO"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 下午3:48
收件人:&nbsp;"XYZliang/HUAWEI-STORE-GO"<HUAWEI-STORE-GO@noreply.github.com&gt;;
抄送:&nbsp;"244083161"<244083161@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XYZliang/HUAWEI-STORE-GO] 帅哥，为什么下载了包后，解压报错了 (#4)





 
emmmmm，没有截图我也不知道。
 压缩包是github自动生成的，一般来说没什么问题，可能是你的压缩软件有问题。
 建议换一个压缩软件，比如Windows下的360压缩（360为数不多的良心软件了），mac下的maczip或者keka
 或者，你直接点开HUAWEI STORE GO.py单独下载这个py脚本就行了。

**Comment by XYZliang** [comment]
试一试[HUAWEI-STORE-GO.zip](https://download.kstore.space/download/2078/HUAWEI-STORE-GO.zip)

**Comment by Newplaer** [comment]
谢谢，这个解压没问题。
过几天试试这个脚本


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XYZliang/HUAWEI-STORE-GO"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 下午5:07
收件人:&nbsp;"XYZliang/HUAWEI-STORE-GO"<HUAWEI-STORE-GO@noreply.github.com&gt;;
抄送:&nbsp;"244083161"<244083161@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [XYZliang/HUAWEI-STORE-GO] 帅哥，为什么下载了包后，解压报错了 (#4)





 
试一试HUAWEI-STORE-GO.zip

**Comment by XYZliang** [comment]
> 谢谢，这个解压没问题。 过几天试试这个脚本
> […](#)

okok～
