### ISSUE TITLE
HUAWEI STORE GO.py V3.1 登录问题

### ISSUE THREAD

**Issue by skklkim** [XYZliang/HUAWEI-STORE-GO#7]
V3.1测试逻辑问题，脚本运行后打开浏览器跳转登录页面，填入账号密码后直接跳转商品页面后再次跳回登录页面

**Comment by XYZliang** [comment]
是的，我刚刚注意到了，登陆部分有问题。当时比较匆忙改错了，会尽快修复，可以暂时用3.0的脚本

**Comment by XYZliang** [comment]
3.2已经修复
